import type { Metadata } from "next";
import "./globals.css";

import LateralMenu from "@/components/lateralMenu";
import Header from "@/components/header";

export const metadata: Metadata = {
	title: "NextJS | Home",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-br">
			<body
				className={`flex text-gray-200`}
			>
				<LateralMenu />

				<div className="w-full flex flex-col gap-10 p-10">
					<Header />

					{children}
				</div>
			</body>
		</html>
	);
}
