import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
	title: "NextJS | Home",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-br">
			<body
				className={`flex flex-col h-screen bg-[#121212] text-white`}
			>
				<Header />

				<div className="flex-1 px-12 py-4">
					{children}
				</div>

				<Footer />
			</body>
		</html>
	);
}
